version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: latest
  commands:
    - python3 -m venv venv
    - . venv/bin/activate
    - pip install sphinx myst_nb sphinx_book_theme maturin
    - maturin develop
    - sphinx-build -b html ./doc/source ./doc/build/html
    - mkdir --parents $READTHEDOCS_OUTPUT
    - mv doc/build/html $READTHEDOCS_OUTPUT/html
